/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTA;

import CONTROLADOR.Cordinador;
import MODELO.VO.ClienteVO;
import javax.swing.JOptionPane;

/**
 *
 * @author alexisruiz
 */
public class ClienteNuevo extends javax.swing.JInternalFrame {
    
private Cordinador miCordinador;
    /**
     * Creates new form Carpeta1
     */
    public ClienteNuevo() {
        initComponents();
        setBounds(20, 10, 600, 500);
        disable();
        jbCancelar.setEnabled(false);
        jbGuardar.setEnabled(false);
        
    }

    
    public void disable(){
        jtfDocumento.setEnabled(false);
        jtfNombres.setEnabled(false);
        jtfApellidos.setEnabled(false);
        jtfFechaNac.setEnabled(false);
        jtfDireccion.setEnabled(false);
        jtfTelefono.setEnabled(false);
        jtaObservacion.setEnabled(false);
        jbCancelar.setEnabled(false);
        jbGuardar.setEnabled(false);
        jbNuevo.setEnabled(true);
        jButton3.setEnabled(true);
    }
    
    public void enable(){
        jtfDocumento.setEnabled(true);
        jtfNombres.setEnabled(true);
        jtfApellidos.setEnabled(true);
        jtfFechaNac.setEnabled(true);
        jtfDireccion.setEnabled(true);
        jtfTelefono.setEnabled(true);
        jtaObservacion.setEnabled(true);
        jbGuardar.setEnabled(true);
        jbCancelar.setEnabled(true);
        jbNuevo.setEnabled(false);
        jButton3.setEnabled(false);
    }
    
    void resetear(){
        jtfDocumento.setText("");
        jtfNombres.setText("");
        jtfApellidos.setText("");
        jtfFechaNac.setText("");
        jtfDireccion.setText("");
        jtfTelefono.setText("");
        jtaObservacion.setText("");
      
    }
    
    void setear(){
        jtfDocumento.setText("Documento");
        jtfNombres.setText("Nombres");
        jtfApellidos.setText("Apellidos");
        jtfFechaNac.setText("Fecha nacimiento");
        jtfDireccion.setText("Direcciòn");
        jtfTelefono.setText("Telefono");
        jtaObservacion.setText("Observaciòn");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jtfDireccion = new javax.swing.JTextField();
        jtfTelefono = new javax.swing.JTextField();
        jtfFechaNac = new javax.swing.JTextField();
        jtfDocumento = new javax.swing.JTextField();
        jtfApellidos = new javax.swing.JTextField();
        jtfNombres = new javax.swing.JTextField();
        jbCancelar = new javax.swing.JButton();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaObservacion = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setIconifiable(true);
        setTitle("REGISTRO CLIENTE NUEVO");
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW CLIENT");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(106, 31, 258, 43);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 8, 470, 100);

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("FORMULARIO"));
        jPanel3.setForeground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(null);

        jtfDireccion.setBackground(new java.awt.Color(204, 204, 255));
        jtfDireccion.setText("DIRECCION");
        jtfDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfDireccionFocusGained(evt);
            }
        });
        jtfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDireccionKeyPressed(evt);
            }
        });
        jPanel3.add(jtfDireccion);
        jtfDireccion.setBounds(230, 130, 140, 19);

        jtfTelefono.setBackground(new java.awt.Color(204, 204, 255));
        jtfTelefono.setText("TELEFONO");
        jtfTelefono.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfTelefonoFocusGained(evt);
            }
        });
        jtfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfTelefonoKeyPressed(evt);
            }
        });
        jPanel3.add(jtfTelefono);
        jtfTelefono.setBounds(20, 130, 140, 19);

        jtfFechaNac.setBackground(new java.awt.Color(204, 204, 255));
        jtfFechaNac.setText("FECHA NACIMIENTO");
        jtfFechaNac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfFechaNacFocusGained(evt);
            }
        });
        jtfFechaNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfFechaNacKeyPressed(evt);
            }
        });
        jPanel3.add(jtfFechaNac);
        jtfFechaNac.setBounds(230, 90, 140, 19);

        jtfDocumento.setBackground(new java.awt.Color(204, 204, 255));
        jtfDocumento.setText("DOCUMENTO");
        jtfDocumento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfDocumentoFocusGained(evt);
            }
        });
        jtfDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfDocumentoKeyPressed(evt);
            }
        });
        jPanel3.add(jtfDocumento);
        jtfDocumento.setBounds(20, 50, 140, 19);

        jtfApellidos.setBackground(new java.awt.Color(204, 204, 255));
        jtfApellidos.setText("APELLIDOS");
        jtfApellidos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfApellidosFocusGained(evt);
            }
        });
        jtfApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfApellidosKeyPressed(evt);
            }
        });
        jPanel3.add(jtfApellidos);
        jtfApellidos.setBounds(20, 90, 140, 19);

        jtfNombres.setBackground(new java.awt.Color(204, 204, 255));
        jtfNombres.setText("NOMBRES");
        jtfNombres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtfNombresFocusGained(evt);
            }
        });
        jtfNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNombresKeyPressed(evt);
            }
        });
        jPanel3.add(jtfNombres);
        jtfNombres.setBounds(230, 50, 140, 20);

        jbCancelar.setText("CANCELAR");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });
        jPanel3.add(jbCancelar);
        jbCancelar.setBounds(230, 260, 105, 25);

        jbGuardar.setAction(jbGuardar.getAction());
        jbGuardar.setText("GUARDAR");
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(jbGuardar);
        jbGuardar.setBounds(30, 260, 100, 30);

        jbNuevo.setText("NUEVO");
        jbNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoActionPerformed(evt);
            }
        });
        jPanel3.add(jbNuevo);
        jbNuevo.setBounds(140, 260, 82, 25);

        jtaObservacion.setBackground(new java.awt.Color(204, 204, 255));
        jtaObservacion.setColumns(20);
        jtaObservacion.setRows(5);
        jtaObservacion.setText("Observacion del cliente");
        jtaObservacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtaObservacionFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(jtaObservacion);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(20, 160, 260, 80);

        jButton3.setText("CERRAR");
        jButton3.setAutoscrolls(true);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(350, 260, 87, 25);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(60, 120, 460, 320);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfDocumentoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDocumentoKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jtfDocumentoKeyPressed

    private void jtfNombresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNombresKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfNombresKeyPressed

    private void jtfApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfApellidosKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfApellidosKeyPressed

    private void jtfFechaNacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfFechaNacKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfFechaNacKeyPressed

    private void jtfTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfTelefonoKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfTelefonoKeyPressed

    private void jtfDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfDireccionKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jtfDireccionKeyPressed

    private void jbNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoActionPerformed
        // TODO add your handling code here:
        enable();
        setear();
    }//GEN-LAST:event_jbNuevoActionPerformed

    private void jtfDocumentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDocumentoFocusGained
        // TODO add your handling code here:
        jtfDocumento.setText("");
    }//GEN-LAST:event_jtfDocumentoFocusGained

    private void jtfNombresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfNombresFocusGained
        // TODO add your handling code here:
       jtfNombres.setText("");
    }//GEN-LAST:event_jtfNombresFocusGained

    private void jtfApellidosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfApellidosFocusGained
        // TODO add your handling code here:
        jtfApellidos.setText("");
    }//GEN-LAST:event_jtfApellidosFocusGained

    private void jtfFechaNacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfFechaNacFocusGained
        // TODO add your handling code here:
        jtfFechaNac.setText("");
    }//GEN-LAST:event_jtfFechaNacFocusGained

    private void jtfTelefonoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfTelefonoFocusGained
        // TODO add your handling code here:
        jtfTelefono.setText("");
    }//GEN-LAST:event_jtfTelefonoFocusGained

    private void jtfDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtfDireccionFocusGained
        // TODO add your handling code here:
        jtfDireccion.setText("");
    }//GEN-LAST:event_jtfDireccionFocusGained

    private void jtaObservacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtaObservacionFocusGained
        // TODO add your handling code here:
        jtaObservacion.setText("");
    }//GEN-LAST:event_jtaObservacionFocusGained

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        miCordinador.cerrarVentanaClienteNuevo();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        resetear();
        disable();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed
        // TODO add your handling code here:
        //Cuando se de click en el boton guardar, se va a ir al cordinador al proceso o  metodo registrar
        registra();
        resetear();
        disable();
    }//GEN-LAST:event_jbGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JTextArea jtaObservacion;
    private javax.swing.JTextField jtfApellidos;
    private javax.swing.JTextField jtfDireccion;
    private javax.swing.JTextField jtfDocumento;
    private javax.swing.JTextField jtfFechaNac;
    private javax.swing.JTextField jtfNombres;
    private javax.swing.JTextField jtfTelefono;
    // End of variables declaration//GEN-END:variables

    public void setCordinador(Cordinador miCordinador) {
        this.miCordinador=miCordinador;
    }

    private void registra() {
       ClienteVO miClienteVO = new ClienteVO();
       miClienteVO.setDocumento(jtfDocumento.getText());
       miClienteVO.setNombres(jtfNombres.getText());
       miClienteVO.setApellidos(jtfApellidos.getText());
       miClienteVO.setFechaNaci(jtfFechaNac.getText());
       miClienteVO.setDireccion(jtfDireccion.getText());
       miClienteVO.setTelefono(jtfTelefono.getText());
       miClienteVO.setObservacion(jtaObservacion.getText());
       
        String retorno;
    retorno = miCordinador.registrarCliente(miClienteVO);
    
    if(retorno.equals("OK")){
        JOptionPane.showMessageDialog(null, "El registro fue exitoso");
    }else{
        JOptionPane.showMessageDialog(null, "El registro no fue exitoso");
    }
       
       
       
    }
}
